### ISSUE TITLE
also checkout tcmalloc?

### ISSUE THREAD

**Issue by schulzchristian** [alexnoe/VieCut#4]
When currently trying to compile I get the following error, but I also don't want to install tcmalloc system wide:
CMake Error at cmake/FindTcmalloc.cmake:43 (message):
  Could NOT find Tcmalloc library
Call Stack (most recent call first):
  CMakeLists.txt:16 (find_package)

Are we currently dependent on tcmalloc or do we have a version that could be output if tcmalloc is not available?

**Comment by alexnoe** [comment]
Using the cmake option -DUSE_TCMALLOC=OFF usage of TCMalloc can be disabled and replaced with 'standard malloc'. Should I default to TCMalloc being off? This slows down multiterminal_cut in some cases.

**Comment by schulzchristian** [comment]
maybe just output this instead of the error?
this way users know what to do fast.

Thanks Alex!

**Comment by alexnoe** [comment]
Sure, can do.

**Comment by alexnoe** [comment]
Added a note to the error, it now reads "Could NOT find Tcmalloc library. Disable using -DUSE_TCMALLOC=off!"
